# Generated by Django 5.1.5 on 2025-02-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('target_muscles', models.CharField(max_length=200)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('distance_related', models.BooleanField(default=False)),
                ('sets_and_repetitions_related', models.BooleanField(default=False)),
            ],
        ),
    ]
