# Generated by Django 5.1.5 on 2025-02-03 21:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('goal', models.CharField(max_length=255, unique=True)),
                ('workout_frequency', models.IntegerField(help_text='Times per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(7)])),
                ('session_duration', models.IntegerField(help_text='Duration in minutes. Daily.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxLengthValidator(1440)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repetitions', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.FloatField(default=0, help_text='duration in hours', validators=[django.core.validators.MinValueValidator(0)])),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercises')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.workoutplan')),
            ],
        ),
    ]
