# Generated by Django 5.1.5 on 2025-02-04 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_rename_exercise_personalizedexercise_exercise_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessgoal',
            old_name='exercise',
            new_name='exercise_id',
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='target_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
