# Generated by Django 5.1.5 on 2025-02-04 11:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_fitnessgoal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
    ]
