# Generated by Django 5.1.5 on 2025-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_fitnessgoal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='deadline',
            field=models.DateField(),
        ),
    ]
